SPEECHES = [
    "The only way to do great work is to love what you do. If you haven't found it yet, keep looking. Don't settle. - Steve Jobs",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "It is during our darkest moments that we must focus to see the light. - Aristotle Onassis",
    "Strive not to be a success, but rather to be of value. - Albert Einstein",
    "The mind is everything. What you think you become. - Buddha",
    "The best way to predict the future is to create it. - Peter Drucker",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "The unexamined life is not worth living. - Socrates",
    "Winning isn’t everything, but wanting to win is. - Vince Lombardi",
    "Whether you think you can or you think you can't, you're right. - Henry Ford",
    "The journey of a thousand miles begins with a single step. - Lao Tzu",
    "I have not failed. I've just found 10,000 ways that won't work. - Thomas A. Edison",
    "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "The secret of getting ahead is getting started. - Mark Twain",
    "The best revenge is massive success. - Frank Sinatra",
    "The greater the obstacle, the more glory in overcoming it. - Molière",
    "What you get by achieving your goals is not as important as what you become by achieving your goals. - Zig Ziglar",
    "It's not whether you get knocked down, it's whether you get up. - Vince Lombardi",
    "If you want to lift yourself up, lift up someone else. - Booker T. Washington",
    "Perseverance is not a long race; it is many short races one after the other. - Walter Elliot",
    "Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence. - Helen Keller",
    "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
    "If you are working on something that you really care about, you don't have to be pushed. The vision pulls you. - Steve Jobs",
    "Success is not final, failure is not fatal: it is the courage to continue that counts. - Winston Churchill",
    "The future starts today, not tomorrow. - Pope John Paul II",
    "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
    "The hardest thing is to start, the easiest thing is to finish. - Jack Ma",
    "We may encounter many defeats but we must not be defeated. - Maya Angelou",
    "Limitations live only in our minds. But if we use our imaginations, our possibilities become limitless. - Jamie Paolinetti",
    "The best way out is always through. - Robert Frost",
    "If I have seen further than others, it is by standing upon the shoulders of giants. - Isaac Newton",
    "Opportunity does not knock, it presents itself when you beat down the door. - Kyle Chandler",
    "Hardships often prepare ordinary people for an extraordinary destiny. - C.S. Lewis",
    "It always seems impossible until it's done. - Nelson Mandela",
    "Your attitude, not your aptitude, will determine your altitude. - Zig Ziglar",
    "Keep your eyes on the stars, and your feet on the ground. - Theodore Roosevelt",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "I can't change the direction of the wind, but I can adjust my sails to always reach my destination. - Jimmy Dean",
    "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
    "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
    "Try not to become a man of success, but rather try to become a man of value. - Albert Einstein",
    "The mind is its own place, and in itself can make a heaven of hell, a hell of heaven. - John Milton",
    "Great works are performed not by strength but by perseverance. - Samuel Johnson",
    "You miss 100% of the shots you don't take. - Wayne Gretzky",
    "The future belongs to those who prepare for it today. - Malcolm X",
    "If opportunity doesn't knock, build a door. - Milton Berle",
    "It's hard to beat a person who never gives up. - Babe Ruth",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh (Alice in Wonderland)",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "Success is the sum of small efforts repeated day in and day out. - Robert Collier",
    "The starting point of all achievement is desire. - Napoleon Hill",
    "Infuse your life with action. Don't wait for it to happen. Make it happen. - Bradley Whitford",
    "The only true wisdom is in knowing you know nothing. - Socrates",
    "The secret to success is to know something nobody else knows. - Aristotle Onassis",
    "We are what we repeatedly do. Excellence, then, is not an act, but a habit. - Aristotle",
    "Innovation distinguishes between a leader and a follower. - Steve Jobs",
    "Logic will get you from A to B. Imagination will take you everywhere. - Albert Einstein",
    "The best way to appreciate your job is to imagine yourself without one. - Oscar Wilde",
    "Fall seven times, stand up eight. - Japanese Proverb",
    "You have within you right now, everything you need to deal with whatever the world can throw at you. - Brian Tracy",
    "What's money? A man is a success if he gets up in the morning and goes to bed at night and in between does what he wants to do. - Bob Dylan",
    "The two most important days in your life are the day you are born and the day you find out why. - Mark Twain",
    "Great things are done by a series of small things brought together. - Vincent Van Gogh",
    "If you want to achieve greatness stop asking for permission. - Anonymous",
    "To live is the rarest thing in the world. Most people exist, that is all. - Oscar Wilde",
    "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. - Steve Jobs",
    "Opportunities don't happen, you create them. - Chris Grosser",
    "The only way to discover the limits of the possible is to go beyond them into the impossible. - Arthur C. Clarke",
    "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "Remember that not getting what you want is sometimes a wonderful stroke of luck. - Dalai Lama",
    "The function of leadership is to produce more leaders, not more followers. - Ralph Nader",
    "Courage is resistance to fear, mastery of fear, not absence of fear. - Mark Twain",
    "I attribute my success to this: I never gave or took any excuse. - Florence Nightingale",
    "The most difficult thing is the decision to act, the rest is merely tenacity. - Amelia Earhart",
    "Dreaming, after all, is a form of planning. - Gloria Steinem",
    "No one can make you feel inferior without your consent. - Eleanor Roosevelt",
    "Challenges are what make life interesting and overcoming them is what makes life meaningful. - Joshua J. Marine",
    "If you want to make your dreams come true, the first thing you have to do is wake up. - J.M. Power",
    "If you can't fly then run, if you can't run then walk, if you can't walk then crawl, but whatever you do you have to keep moving forward. - Martin Luther King Jr.",
    "The question isn't who is going to let me; it's who is going to stop me. - Ayn Rand",
    "Build your own dreams, or someone else will hire you to build theirs. - Farrah Gray",
    "Develop success from failures. Discouragement and failure are two of the surest stepping stones to success. - Dale Carnegie",
    "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty. - Winston Churchill",
    "Don't let yesterday take up too much of today. - Will Rogers",
    "We are what we pretend to be, so we must be careful what we pretend to be. - Kurt Vonnegut",
    "People who are crazy enough to think they can change the world, are the ones who do. - Rob Siltanen",
    "You are the master of your destiny. You can influence, direct and control your own environment. You can make your life what you want it to be. - Napoleon Hill",
    "To be a champ, you have to believe in yourself when nobody else will. - Sugar Ray Robinson",
    "The mind is not a vessel to be filled, but a fire to be kindled. - Plutarch",
    "What seems to us as bitter trials are often blessings in disguise. - Oscar Wilde",
    "Don't limit your challenges. Challenge your limits. - Jerry Dunn",
    "The best way to gain self-confidence is to do what you are afraid to do. - Swamy Vivekananda",
    "If you don't design your own life plan, chances are you'll fall into someone else's plan. And guess what they have planned for you? Not much. - Jim Rohn",
    "Nothing is impossible, the word itself says 'I'm possible'! - Audrey Hepburn",
    "The power of imagination makes us infinite. - John Muir",
    "If you have a dream, don’t just sit there. Gather courage to believe that you can succeed and leave no stone unturned to make it a reality. - Dr. Roopleen",
    "The future belongs to the competent. Get good, get better, be the best! - Brian Tracy",
    "Do not wait for a leader; do it alone, person to person. - Mother Teresa",
    "Change your thoughts and you change your world. - Norman Vincent Peale",
    "The secret of change is to focus all your energy not on fighting the old, but on building the new. - Socrates (Peaceful Warrior)",
    "Action is the foundational key to all success. - Pablo Picasso",
    "Setting goals is the first step in turning the invisible into the visible. - Tony Robbins"
]